// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#include "nativium/core/NTVCoreApplicationCore.hpp"  // my header

namespace djinni_generated {

em::val NTVCoreApplicationCore::cppProxyMethods() {
    static const em::val methods = em::val::array(std::vector<std::string> {
        "getVersion",
    });
    return methods;
}

em::val NTVCoreApplicationCore::shared() {
    auto r = ::nativium::core::ApplicationCore::shared();
    return ::djinni_generated::NTVCoreApplicationCore::fromCpp(r);
}
std::string NTVCoreApplicationCore::getVersion(const CppType& self) {
    auto r = self->getVersion();
    return ::djinni::String::fromCpp(r);
}

EMSCRIPTEN_BINDINGS(nativium_core_application_core) {
    em::class_<::nativium::core::ApplicationCore>("ApplicationCore")
        .smart_ptr<std::shared_ptr<::nativium::core::ApplicationCore>>("ApplicationCore")
        .function("nativeDestroy", &NTVCoreApplicationCore::nativeDestroy)
        .class_function("shared", NTVCoreApplicationCore::shared)
        .function("getVersion", NTVCoreApplicationCore::getVersion)
        ;
}

}  // namespace djinni_generated
